### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by tuanta** [Openroadvietnam/pgp-zimlet#2]
i18n support for OpenPGP zimlet, following these guidelines: http://wiki.zimbra.com/wiki/ZCS_6.0:Zimlet_Developers_Guide:Internationalization

Code would be done in i18n-support branch, test, merge into master, then contribute to the upstream by a pull request.

**Comment by barrydegraaff** [comment]
https://bugzilla.zimbra.com/show_bug.cgi?id=97708
